# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'Ubuntu-latest'

container: 
  image: python:3.7
  options: -u root

steps:
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: './test.py'

- task: DownloadSecureFile@1
  name: SettingProfile
  displayName: 'Downloading my_profile for Snowflake'
  inputs:
    secureFile: 'my_profiles.yml'

- script: |
    echo Installing $(SettingProfile.secureFilePath) to the ~/.dbt...
    mkdir ~/.dbt
    cp $(SettingProfile.secureFilePath) ~/.dbt/profiles.yml
  displayName: put my_profile to the right location in ubuntu
    
- script: |
    pip install dbt --user
    export PATH=$PATH:/home/vsts_azpcontainer/.local/bin
    cd dbt_snowflake_demo_i 
    dbt debug
    dbt seed
    dbt run
    dbt test
  displayName: 'DBT install then run and test'

- script: |
    echo Pipeline has finished!